apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
  labels:
    account: details #By default, pods use the default ServiceAccount in the namespace. However, for more granular control or for separating concerns, creating a specific ServiceAccount like bookinfo-details allows for custom configurations and permissions.
